<?php

/**
 * Implements hook_entity_info().
 */
function stock_entity_info() {

  $return = array(
    'stock_out' => array(
      'label' => t('Stock Out'),
      'controller class' => 'StockOutController',
      'base table' => 'stock_out',
      'fieldable' => FALSE,
      'entity keys' => array(
        'id' => 'id',
      ),
      'views controller class' => 'StockOutViewsController',
      'view modes' => array(
        'full' => array(
          'label' => t('Full content'),
          'custom settings' => TRUE,
        ),
      ),
    ),
  );

  $return = array(
    'stock_in' => array(
      'label' => t('Stock In'),
      'controller class' => 'StockInController',
      'base table' => 'stock_out',
      'fieldable' => FALSE,
      'entity keys' => array(
        'id' => 'id',
      ),
      'views controller class' => 'StockInViewsController',
      'view modes' => array(
        'full' => array(
          'label' => t('Full content'),
          'custom settings' => TRUE,
        ),
      ),
    ),
  );

  return $return;
}

/**
 * Implements hook_menu().
 */
function stock_menu() {
  $items['stock/add'] = array(
    'title' => 'Enter the warehouse',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stock_add_form', 2),
    'access arguments' => array('stock:*:add'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'includes/stock.page.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function stock_permission() {
  return array(
    'stock:*:add' =>  array(
      'title' => t('Enter the warehouse'),
    ),
    'stock:*:manage' => array(
      'title' => t('Quản lí kho'),
    ),
  );
}

/**
 * Implement stock_create.
 */
function stock_create($type, $entity) {
  return entity_save($type, $entity);
}

/**
 * Implement stock_save update.
 */
function stock_save($type, $entity) {
  return entity_save($type, $entity);
}

/**
 * @param $ids
 * @param $conditions
 * @return mixed
 * Implements load cook table with condition
 */
function stock_load_multiple_with_conditions($ids, $conditions, $type)
{
  return entity_load($type, $ids, $conditions);
}

/**
 * Implement stock_delete.
 */
function stock_delete($type, $id) {
  return entity_delete($type, $id);
}

/**
 * @param $id
 * Implement hook_entity_load.
 */
function stock_load($type, $id) {
  $entity = stock_load_multiple(array($id), $type);
  return reset($entity);
}
/**
 * Implement Stock Load Multiple
 * @param $ids = array();
 */
function stock_load_multiple($ids, $type) {
  return entity_load($type, $ids);
}

/**
 * Implement check exit cook table
 */
function stock_get_stock($field, $value, $type)
{
  $query = db_select($type, 'd');
  $query->fields('d');
  $query->condition($field, $value, '=');
  $result = $query->execute()->fetchAll();
  if ($result) {
    return $result;
  } else {
    return false;
  }
}
